cart/urls.py
from django.urls import path

from cart.views import CartView, AddProductToCartByProductIdView, AddProductToCartBySellerIdView,\
    DeleteProductFromCartView, ChangePriceAjax, ChangeCountAjax

zapp_name = "cart"

urlpatterns = [
    path("", CartView.as_view(), name="mycart"),
    path(
        "add/<int:id>",
        AddProductToCartByProductIdView.as_view(),
        name="add",
    ),
    path(
        "remove/<int:id>",
        DeleteProductFromCartView.as_view(),
        name="remove",
    ),
    path(
        'change_price',
        ChangePriceAjax.as_view(),
        name='change_price'
    ),
    path(
        'change_count',
        ChangeCountAjax.as_view(),
        name='change_count'
    ),
    path(
        "add/<int:pid>/<int:id>",
        AddProductToCartBySellerIdView.as_view(),
        name="addbysellerid",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/clearcache/', include('banners.urls')),
    path('admin/', admin.site.urls),
    path('', include('customers.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('goods/', include('goods.urls')),
    path('banners/', include('banners.urls')),
    path('customers/', include('customers.urls')),
    path('', include('app_shop.urls')),
    path('orders/', include('orders.urls')),
    path('sale/', include('discounts.urls')),
    path('import/', include('data_import.urls')),
    path('i18n', include('django.conf.urls.i18n')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.utils.translation import gettext_lazy as _
from django.db import models
from goods.models import GoodsInMarket, Category
from discounts.models import Discount
User = get_user_model()


def get_disc(disc: Discount, price: float) -> float:
    if disc.discount_mech_id == 1:
        # если скидка в процентах
        return round(price * disc.discount_value / 100)
    elif disc.discount_mech_id == 2:
        # если скидка в рублях
        return price - disc.discount_value
    else:
        # если скидка - фиксированная сумма
        return disc.discount_value


def price_with_discount(goods_in_market: GoodsInMarket, category: Category) -> float:
    price = goods_in_market.price
    goods = goods_in_market.goods
    disc = Discount.objects.filter(
        Q(discount_type=1),
        Q(goods_1=goods) | Q(category_1=category)
    ).order_by('-weight').first()
    if disc:
        discount = get_disc(disc, price)
    else:
        discount = 0
    return price - discount


class CartItems(models.Model):
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE, related_name="user_for_cart")
    product_in_shop = models.ForeignKey(GoodsInMarket,
                                        null=True,
                                        on_delete=models.CASCADE,
                                        verbose_name="Товар в магазине",
                                        related_name="product_in_shop_for_cart")
    quantity = models.PositiveIntegerField(verbose_name='количество', default=1)
    category = models.ForeignKey(Category, verbose_name=_('category'), on_delete=models.CASCADE, related_name='category_in_cart', null=True)

    @property
    def discount_price(self):
        new_price = price_with_discount(self.product_in_shop, self.category)
        return new_price

    class Meta:
        verbose_name_plural = "Корзина"

    def __str__(self):
        return f"{self.product_in_shop} {self.user}"

cart/views.py
from django.core.cache import cache
from django.core.handlers.wsgi import WSGIRequest
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import View

from cart.models import CartItems
from cart.services import new_price_and_total_price, add_product_to_cart_by_product_id, cart_price, change_count, \
    add_product_to_cart_by_seller_id, from_session_todb

class AddProductToCartByProductIdView(View):
    """
    Добавление продукта в корзину
    """
    def get(self, request: WSGIRequest, id: int, *args, **kwargs):
        cache.delete('total_price')
        product_id = id
        add_product_to_cart_by_product_id(request, product_id, 1)
        return redirect(request.META['HTTP_REFERER'])

    def post(self, request: WSGIRequest, *args, **kwargs):
        cache.delete('total_price')
        product_id = request.POST.get('product_id')
        quantity = request.POST.get('count')
        add_product_to_cart_by_product_id(request, product_id, quantity)
        total_price_disc, total_price, shops, cart = cart_price(request)
        return JsonResponse({'total_price_disc': total_price_disc}, status=200)


class AddProductToCartBySellerIdView(View):
    """
    Добавление продукта в корзину
    """
    def get(self, request: WSGIRequest, pid: int, id: int, *args, **kwargs):
        cache.delete('total_price')
        seller_id = id
        product_id = pid
        add_product_to_cart_by_seller_id(request, product_id, seller_id, 1)
        return redirect(request.META['HTTP_REFERER'])



class DeleteProductFromCartView(View):
    """
    Удаление продукта из корзины
    """
    def get(self, request: WSGIRequest, id: int,  *args, **kwargs):
        cache.delete('total_price')
        product_id = id
        if request.user.is_authenticated:
            item = CartItems.objects.get(product_in_shop__goods_id=product_id, user=request.user)
            item.delete()
        else:
            for item in request.session["cart"]:
                if int(item["product_id"]) == product_id:
                    item.clear()
            while {} in request.session["cart"]:
                request.session["cart"].remove({})
            request.session.modified = True
        return redirect('/cart')


class CartView(View):
    """
    Представление корзины
    """
    def get(self, request: WSGIRequest, *args, **kwargs):
        from_session_todb(request)
        total_price = cache.get('total_price')
        if total_price is not None:
            total_price_disc = cache.get('total_price_disc')
            total_price = cache.get('total_price')
            shops = cache.get('shops')
            cart = cache.get('cart')
        else:
            total_price_disc, total_price, shops, cart = cart_price(request)
        return render(request, 'cart/cart.html', {'cart': cart,
                                                  'shops': shops,
                                                  'total_price': total_price,
                                                  'total_price_disc': total_price_disc})


class ChangePriceAjax(View):
    """
     Изменение цены товара в корзине через ajax
     """
    def post(self, request: WSGIRequest, *args, **kwargs):
        price = new_price_and_total_price(request)
        total_price_disc, total_price, shops, cart = cart_price(request)
        return JsonResponse({'data': price,
                             'total_price': total_price,
                             'total_price_disc': total_price_disc}, status=200)


class ChangeCountAjax(View):
    """
    Изменение количества товара в корзине через ajax
    """
    def post(self, request: WSGIRequest, *args, **kwargs):
        product_id = request.POST.get('product_id')
        count_of_product = request.POST.get('count_of_product')
        change_count(request, int(product_id), int(count_of_product))
        total_price_disc, total_price, shops, cart = cart_price(request)
        return JsonResponse({'total_price': total_price,
                             'total_price_disc': total_price_disc}, status=200)

templates/cart/cart.html
{% extends 'base.html' %}
{% block header %}
    {% include 'elements/header.html' %}
{% endblock %}
{% block content %}
{%  csrf_token %}
<div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Корзина
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Корзина</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
        <div class="wrap">
            <form class="form Cart" action="#" method="post" name="cart_order">
                {% if cart%}
                    {% for item in cart %}
                        <div class="Cart-product">
                            <div class="Cart-block Cart-block_row">
                                <div class="Cart-block Cart-block_pict"><a class="Cart-pict" href="#"><img class="Cart-img" src="{{ item.product_in_shop.goods.goods_image.first.image.url }}" alt="card.jpg"></a>
                                </div>
                                <div class="Cart-block Cart-block_info"><a class="Cart-title" href="{% url 'detail' item.product_in_shop.goods.id %}"> {{ item.product_in_shop.goods.name }}</a>
                                    <div class="Cart-desc">
                                    </div>
                                </div>
                                <div class="Cart-block Cart-block_price">
                                        {% if item.discount_price < item.product_in_shop.price %}
                                            <div class="Cart-price Cart-price_old">{{ item.product_in_shop.price }}руб</div>
                                        {% endif %}
                                        <div class="Cart-price" id="{{ item.product_in_shop.goods.id }}">{{ item.discount_price }}руб</div>
                                </div>
                            </div>
                            <div class="Cart-block Cart-block_row">
                                <div class="Cart-block Cart-block_seller">
                                    <div class="form-selectWrap">
                                        <select id="select" class="form-select" name="seller">
                                                  {% for key, value in shops.items %}
                                                      {% if key == item.product_in_shop.goods.id  %}
                                                          {% for shop in value %}
                                                              {% if shop.seller.title == item.product_in_shop.seller.title %}
                                                                  <option value="{{ item.product_in_shop.goods.id }}" selected="selected"> {{ shop.seller.title }}
                                                                  </option>
                                                              {% else %}
                                                                  <option value="{{ item.product_in_shop.goods.id }}"> {{ shop.seller.title }}
                                                                  </option>
                                                              {% endif %}
                                                          {% endfor %}
                                                      {% endif %}
                                           {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="Cart-block Cart-block_amount">
                                    <div class="Cart-amount">
                                        <div class="Amount">
                                            <button class="Amount-remove" value="{{ item.product_in_shop.goods.id }}amount" type="button">
                                            </button>
                                            <input id="{{ item.product_in_shop.goods.id }}amount" class="Amount-input form-input" name="amount{{ item.product_in_shop.goods.id }}" type="text" value="{{ item.quantity }}">
                                            <button class="Amount-add" value="{{ item.product_in_shop.goods.id }}amount" type="button">
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div class="Cart-block Cart-block_delete">
                                    <a class="Cart-delete" href="{% url 'cart:remove' item.product_in_shop.goods.id %}">
                                        <img src="/static/assets/img/icons/card/delete.svg" alt="change.svg">
                                    </a>
                                </div>
                            </div>

                        </div>

                    {% endfor %}


                    <div class="Cart-total">
                        <div class="Cart-block Cart-block_total">
                            <strong class="Cart-title">Итого:</strong>
                            <span class="Cart-price" id="prev_price_with_discount">{{ total_price_disc }} руб</span>
                            {% if total_price_disc < total_price %}
                                <span class="Cart-price_old" id="prev_price">{{ total_price }} руб</span>
                            {% endif %}
                        </div>
                        <div class="Cart-block"><a class="btn btn_success btn_lg" href="../orders/add_order">Оформить заказ</a>
                        </div>
                    </div>
                {% else %}
                    Корзина пуста
                {% endif %}
            </form>
        </div>
      </div>
    </div>

<script>
$(document).ready(function (){
    var csrf = $("input[name=csrfmiddlewaretoken]").val();
    $(".form-select").change(function(){
        var product=$(this).val();
        console.log(product)
        $.ajax({
            url: '{% url "cart:change_price" %}',
            method: 'post',
            dataType: 'json',
            data: {
                product_id: $(this).val(),
                shop: $(this).find('option:selected').text(),
                csrfmiddlewaretoken: csrf
            },
            success: function (response) {
                document.getElementById(product).textContent = response.data
                document.getElementById(product).textContent += ' руб'
                var discount_price = document.getElementById('prev_price')
                if (discount_price !== null) {
                    discount_price.textContent = response.total_price
                    discount_price.textContent += ' руб'
                }
                document.getElementById('prev_price_with_discount').textContent = response.total_price_disc
                document.getElementById('prev_price_with_discount').textContent += ' руб'
                document.getElementById('CartBlock-price').textContent = response.total_price_disc
                document.getElementById('CartBlock-price').textContent += ' руб'
            }
        })
    });
})
</script>
<script>
$(document).ready(function (){
    var csrf = $("input[name=csrfmiddlewaretoken]").val();
    $(".Amount-add").click(function(){
        var id_of_product=$(this).val()
        var count = $('#'+id_of_product).val()
        console.log(parseInt(id_of_product))
        console.log(parseInt(count)+1)
        $.ajax({
            url: '{% url "cart:change_count" %}',
            method: 'post',
            dataType: 'json',
            data: {
                product_id: parseInt(id_of_product),
                count_of_product: (parseInt(count)+1),
                csrfmiddlewaretoken: csrf
            },
            success: function (response) {
                var discount_price = document.getElementById('prev_price')
                if (discount_price !== null) {
                    discount_price.textContent = response.total_price
                    discount_price.textContent += ' руб'
                }
                document.getElementById('prev_price_with_discount').textContent = response.total_price_disc
                document.getElementById('prev_price_with_discount').textContent += ' руб'
                document.getElementById('CartBlock-price').textContent = response.total_price_disc
                document.getElementById('CartBlock-price').textContent += ' руб'
            }
        })
    });


    $(".Amount-remove").click(function(){
        var id_of_product=$(this).val()
        var count = $('#'+id_of_product).val()
        $.ajax({
            url: '{% url "cart:change_count" %}',
            method: 'post',
            dataType: 'json',
            data: {
                product_id: parseInt(id_of_product),
                count_of_product: (parseInt(count)-1),
                csrfmiddlewaretoken: csrf
            },
            success: function (response) {
                var discount_price = document.getElementById('prev_price')
                if (discount_price !== null) {
                    discount_price.textContent = response.total_price
                    discount_price.textContent += 'руб'
                }
                document.getElementById('prev_price_with_discount').textContent = response.total_price_disc
                document.getElementById('prev_price_with_discount').textContent += ' руб'
                document.getElementById('CartBlock-price').textContent = response.total_price_disc
                document.getElementById('CartBlock-price').textContent += ' руб'
            }
        })
    });
})
</script>
{% endblock %}
{% block footer %}
     {% include 'elements/footer.html' %}
{% endblock %}

templates/cart/cart_list.html
{% extends 'base.html' %}
{% block header %}
    {% include 'elements/header.html' %}
{% endblock %}
{% block content %}
{%  csrf_token %}
<div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Корзина
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">home{{ object.old_cost }}</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>{{ cart.old_cost }}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
        <div class="wrap">
            <form class="form Cart" action="#" method="post" name="cart_order">
                {% for item in cart_list.cart %}
                        <div class="Cart-product">
                            <div class="Cart-block Cart-block_row">
                                <div class="Cart-block Cart-block_pict">
                                    <a class="Cart-pict" href="{{ item.goods.get_absolute_url }}">
                                        <img class="Cart-img" src="{{ item.goods.image.url }}" alt="card.jpg">
                                    </a>
                                </div>
                                <div class="Cart-block Cart-block_info">
                                    <a class="Cart-title" href="{{ item.goods.get_absolute_url }}"> {{ item }}</a>
                                    <div class="Cart-desc"> item
                                    </div>
                                </div>
                                <div class="Cart-block Cart-block_price">
                                    {% if item.3 %}
                                        <div class="Cart-price Cart-price_old" id="{{ key.id }}">
                                            {{ item.0 }}руб
                                        </div>
                                    {% endif %}
                                    <div class="Cart-price">
                                        {{ item.1 }}
                                    </div>
                                </div>
                            </div>
                            <div class="Cart-block Cart-block_row">
                                <div class="Cart-block Cart-block_seller">
                                    <div class="form-selectWrap">
                                        <select id="select" class="form-select" name="seller">
                                            {% for shop in value %}
                                                <option value="{{ key.id }}"> {{ shop.title }}
                                                </option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="Cart-block Cart-block_amount">
                                    <div class="Cart-amount">
                                        <div class="Amount">
                                            <button class="Amount-remove" value="{{ key.id }}amount" type="button">
                                            </button>
                                            <input id="{{ key.id }}amount" class="Amount-input form-input" name="amount{{ key.id }}" type="text" value="{{ value.2 }}">
                                            <button class="Amount-add" value="{{ key.id }}amount" type="button">
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div class="Cart-block Cart-block_delete">
                                    <a class="Cart-delete" href="{% url 'cart:remove' key.id %}">
                                        <img src="/static/assets/img/icons/card/delete.svg" alt="change.svg">
                                    </a>
                                </div>
                            </div>

                        </div>
                {% endfor %}


                <div class="Cart-total">
                    <div class="Cart-block Cart-block_total">
                        <strong class="Cart-title">Итого:
                        </strong><span class="Cart-price">{{ total_price }}руб</span><span class="Cart-price_old" id="prev_price">{{ old_total_price }}руб</span>
                    </div>
                    <div class="Cart-block"><a class="btn btn_success btn_lg" href="order.html">Оформить заказ</a>
                    </div>
                </div>
            </form>
        </div>
      </div>
    </div>

<script>
$(document).ready(function (){
    var csrf = $("input[name=csrfmiddlewaretoken]").val();
    $(".form-select").change(function(){
        var product=$(this).val();
        $.ajax({
            url: '{% url "cart:change_price" %}',
            method: 'post',
            dataType: 'json',
            data: {
                product_id: $(this).val(),
                shop: $(this).find('option:selected').text(),
                csrfmiddlewaretoken: csrf
            },
            success: function (response) {
                document.getElementById(product).textContent = response.data
                var total_price = 0
                $(".Cart-price_old").each(function(){
                    var price = parseInt(this.textContent.replace('руб', ''))
                    var price_id = parseInt($(this).attr('id'))
                    $(".Amount-input").each(function(){
                        var id_from_input = parseInt($(this).attr('id'))
                        var count = parseInt($(this).val())
                        if (id_from_input === price_id) {
                            total_price += (price * count)
                        }
                    })
                })
                document.getElementById('prev_price').textContent = total_price
            }
        })
    });
})
</script>
<script>
$(document).ready(function (){

    $(".Amount-add").click(function(){
        var id_of_product=$(this).val()
        var price = document.getElementById(parseInt(id_of_product)).textContent.replace('руб', '')
        var total_price = parseInt(document.getElementById('prev_price').textContent)
        total_price += parseInt(price)
        document.getElementById('prev_price').textContent = total_price
    });


    $(".Amount-remove").click(function(){
        var id_of_product=$(this).val()
        var price = document.getElementById(parseInt(id_of_product)).textContent.replace('руб', '')
        var total_price = parseInt(document.getElementById('prev_price').textContent)
        total_price -= parseInt(price)
        document.getElementById('prev_price').textContent = total_price
    });
})
</script>
{% endblock %}
{% block footer %}
     {% include 'elements/footer.html' %}
{% endblock %}