cart/urls.py
from django.urls import path

from cart.views import CartView, AddProductToCartByProductIdView, AddProductToCartBySellerIdView,\
    DeleteProductFromCartView, ChangePriceAjax, ChangeCountAjax

zapp_name = "cart"

urlpatterns = [
    path("", CartView.as_view(), name="mycart"),
    path(
        "add/<int:id>",
        AddProductToCartByProductIdView.as_view(),
        name="add",
    ),
    path(
        "remove/<int:id>",
        DeleteProductFromCartView.as_view(),
        name="remove",
    ),
    path(
        'change_price',
        ChangePriceAjax.as_view(),
        name='change_price'
    ),
    path(
        'change_count',
        ChangeCountAjax.as_view(),
        name='change_count'
    ),
    path(
        "add/<int:pid>/<int:id>",
        AddProductToCartBySellerIdView.as_view(),
        name="addbysellerid",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/clearcache/', include('banners.urls')),
    path('admin/', admin.site.urls),
    path('', include('customers.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('goods/', include('goods.urls')),
    path('banners/', include('banners.urls')),
    path('customers/', include('customers.urls')),
    path('', include('app_shop.urls')),
    path('orders/', include('orders.urls')),
    path('sale/', include('discounts.urls')),
    path('import/', include('data_import.urls')),
    path('i18n', include('django.conf.urls.i18n')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from config.settings import CACHES_TIME

from .views import ShowDetailProduct, CompareView, AddProductToCompareView, Catalog, \
    HistoryList, DeleteProductFromCompareView, GoodsClearCacheAdminView
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('catalog/', Catalog.as_view(), name='catalog'),
    path('historyview/', HistoryList.as_view(), name='historyview'),
    path('compare/', CompareView.as_view(), name='compare'),
    path("compare_add/<int:id>", AddProductToCompareView.as_view(), name="compare_add"),
    path("compare_delete/<int:id>", DeleteProductFromCompareView.as_view(), name="compare_delete"),
    path('detail/<int:pk>/', ShowDetailProduct.as_view(), name='detail'),
    path('goods_clear_cache/', GoodsClearCacheAdminView.as_view(), name="goodsclearcache"),
]

goods/forms.py
from django import forms
from goods.models import DetailProductComment
from django.utils.translation import gettext as _


class DetailProductReviewForm(forms.Form):
    email = forms.EmailField(max_length=54, help_text=_('Enter your email address'), label='email')
    author_name = forms.CharField(max_length=30, label='full_name')
    text = forms.CharField(max_length=700, label='detail_review')

goods/views.py
import datetime
import decimal

from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.core.handlers.wsgi import WSGIRequest
from django.db.models import Q, QuerySet
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView
from django.views.generic import DetailView
from app_shop.models import Seller
from banners.utils import clear_cache
from cart.models import CartItems
from .forms import DetailProductReviewForm

from .models import SuperCategory
from .models import GoodsInMarket, DetailProductComment, Image
from django.utils.translation import gettext as _
from .models import Goods, ViewHistory
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from config.settings import CACHES_TIME
from goods.serviсes import CatalogMixin, create_compare, get_all_features, get_different_features
from discounts.models import Discount


class CategoryView(View):
    """
    Представление для категорий товаров у которых activity = True.
    """

    def get(self, request: WSGIRequest) -> HttpResponse:
        cache_this = cache_page(3600 * CACHES_TIME)
        categories = SuperCategory.objects.filter(activity=True)
        if categories.update():
            cache.delete(cache_this)
        return render(request, 'category/category.html', context={'categories': categories})


class Catalog(CatalogMixin, ListView):
    model = Goods
    template_name = 'goods/catalog.html'
    paginate_by = 8
    context_object_name = 'catalog'

    def get_queryset(self) -> QuerySet:
        queryset = self.select_orm_statement()
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super().get_context_data()
        parameters = self.normalises_values_parameters()
        context.update(parameters)
        context.update({'sellers': Seller.objects.all()})
        context.update({'supercategory': SuperCategory.objects.all()})
        return context


class ShowDetailProduct(DetailView):
    """
    Данный класс служит для детального представления определённого товара
    """
    model = Goods
    template_name = 'goods/product.html'

    def get_context_data(self, **kwargs) -> dict:
        context = super(ShowDetailProduct, self).get_context_data(**kwargs)
        product_id = context['goods'].id

        context['seller'] = GoodsInMarket.objects.filter(goods__id=product_id)
        context['review'] = DetailProductComment.objects.filter(goods__id=product_id)
        context['len_review'] = str(len(context['review']))
        context['images'] = Image.objects.filter(product_id=product_id)
        context['image_pict_right'] = context['images'].first()
        context['form'] = DetailProductReviewForm()
        context['feature'] = Goods.objects.get(id=product_id).feature.all()


        if self.request.user.is_authenticated:
            context['in_cart_or_not'] = CartItems.objects.filter(user=self.request.user,
                                                                 product_in_shop__goods_id=product_id).exists()
            add_to_view_history(self.request.user, context['goods'])
        else:
            cart = list()
            if self.request.session.get("cart"):
                cart = self.request.session.get("cart")
            for result, dic_ in enumerate(cart):
                if dic_.get('inplay', '') == 'False':
                    context['in_cart_or_not'] = True
                    break
                else:
                    context['in_cart_or_not'] = False
        return context

    def post(self, request: WSGIRequest, pk) -> HttpResponseRedirect:
        form = DetailProductReviewForm(request.POST)
        if form.is_valid():
            DetailProductComment.objects.create(
                goods=Goods.objects.get(id=pk),
                text=form.cleaned_data.get('text'),
                email=form.cleaned_data.get('email'),
                author_name=form.cleaned_data.get('author_name')
            )
            return redirect(f"../{pk}/")
        else:
            return redirect(f"../{pk}/")


class AddProductToCompareView(View):
    """
    Добавление товара в сравнение
    """
    def get(self, request: WSGIRequest, id: int, *args, **kwargs) -> HttpResponseRedirect:
        if not request.session.get("compare"):
            request.session["compare"] = list()
        if id not in request.session['compare']:
            request.session['compare'].append(id)
            request.session.modified = True
        else:
            request.session['compare'].remove(id)
            request.session.modified = True
        return redirect(request.META['HTTP_REFERER'])


class DeleteProductFromCompareView(View):
    """
    Удаление товара из списка сравнений
    """

    def get(self, request: WSGIRequest, id: int, *args, **kwargs) -> HttpResponseRedirect:
        id_product = int(id)
        if id_product in request.session["compare"]:
            request.session["compare"].remove(id_product)
            request.session.modified = True
        return redirect('compare')


class CompareView(View):
    """
    Функция получения всех характеристик товаров и проверка категорий сравниваемых товаров
    """
    def get(self, request: WSGIRequest, *args, **kwargs) -> HttpResponse:
        compare_list = request.session.get("compare")
        if compare_list is not None:
            compare_list_products, categories_list, product_features = create_compare(compare_list)
            if len(set(categories_list)) > 1:
                context = {
                    'compare_list': compare_list_products,
                    'different_features': 0,
                    'message': _('It is impossible to compare products from different categories')
                }
                return render(request, 'goods/mycompare.html', context=context)
            all_features = get_all_features(product_features)
            different_features = get_different_features(all_features, compare_list)
            return render(request, 'goods/mycompare.html', {'compare_list': compare_list_products,
                                                            'different_features': different_features})
        else:
            return render(request, 'goods/mycompare.html')


def add_to_view_history(customer, goods: Goods) -> None:
    """
    Метод добавления товара в список просмотренных
    :param customer: покупатель
    :param goods: просмотренный товар
    :return: None
    """
    ViewHistory.objects.update_or_create(customer=customer,
                                         goods=goods,
                                         defaults={'last_view': datetime.datetime.now()})


def remove_from_view_history(customer, goods: Goods) -> None:
    """
    Удаление из истории просмотров
    :param customer: покупатель
    :param goods: товар
    :return: None
    """
    ViewHistory.objects.delete(customer=customer, goods=goods)


def is_in_view_history(customer, goods: Goods) -> bool:
    if ViewHistory.objects.get(customer=customer, goods=goods):
        return True
    else:
        return False


class HistoryList(ListView):
    """
    Страница просмотра истории просмотра товаров. Для просмотра выбирается последние 20 товаров.
    """
    model = ViewHistory
    template_name = 'goods/historyview.html'
    context_object_name = 'goods_list'
    paginate_by = 8

    def get_queryset(self)->QuerySet:
        res = Goods.objects.filter(id__in=ViewHistory.objects.filter(customer=self.request.user)[:20].values_list('goods'))
        return res


def price_with_discount(goods: Goods, old_price=0.00) -> decimal:
    """
    Метод для расчета скидки по товару. Если не указана старая цена, выбирается максимальная из всех предложенных.
    Выбираются все действующие скидки на товар, или на его категорию, возвращается цена с максимальной скидкой,
    но не меньше 1 руб.
    :param goods: товар, по которому ищем цену
    :param old_price: старая цена
    :return: цена с учетом скидки
    """
    if not old_price:
        old_price = GoodsInMarket.objects.filter(goods=goods).aggregate(max('price'))
    today = datetime.date.today()
    goods_discounts = Discount.objects.filter(Q(goods_1=goods) | Q(category_1=goods.category),
                                              discount_type__pk=1,
                                              date_start__lte=today,
                                              date_end__gte=today
                                              )
    percent_discount = goods_discounts.objects.filter(discount_mech__pk=1).aggregate(max('discount_value'))
    percent_discount_price = round((1 - percent_discount) / 100 * old_price, 2)
    absolute_discount = goods_discounts.objects.filter(discount_mech__pk=2).aggregate(max('discount_value'))
    absolute_discount_price = old_price - absolute_discount
    if absolute_discount_price <= 0:
        return 1.00
    if percent_discount_price < absolute_discount_price:
        return percent_discount_price
    return absolute_discount_price


def cart_cost(cart: dict) -> dict:
    """
    Метод получает в качестве параметра словарь вида «товар и исходная цена» и пытается применить
    самую приоритетную скидку на корзину или на набор. Если такая скидка есть, то применяется она; если нет,
    то тогда метод получает цену на каждый товар словаря.
    :param cart: {товар: исходная цена}
    :return: {товар: исходная цена, цена со скидкой, применена ли скидка}
    :rtype: dict
    """
    today = datetime.date.today()
    goods_count = len(cart)
    goods_cost = sum(cart.values())
    cart_discount = Discount.objects.filter(Q(discount_type__pk=3),
                                            date_start__lte=today,
                                            date_end__gte=today,

templates/goods/card.html
{% load static %}
{% load i18n %}

<div class="Card">
    <a class="Card-picture" href="{{ goods.get_absolute_url }}">
        <img src="{{ goods.goods_image.first.image.url }}" alt="card.jpg"/>
    </a>
    <div class="Card-content">
        <strong class="Card-title"><a href="{{ goods.get_absolute_url }}"> {{ goods.name }} </a>
        </strong>
        <div class="Card-description">
            <div class="Card-cost"><span class="Card-price"> {{ goods.price }} {% translate "руб." %}</span>
            </div>
            <div class="Card-category"> {{ goods.category.title }}
            </div>
            <div class="Card-hover"><a class="Card-btn" href="{{ goods.get_absolute_url }}"><img src="{% static 'assets/img/icons/card/bookmark.svg' %}" alt="bookmark.svg"/></a><a class="Compare-btn" id="cart" product_id="{{ goods.id }}" href="{% url 'cart:add' goods.id %}"><img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/></a><a class="Card-btn" href="{% url 'compare_add' goods.id %}"><img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg"/></a>
            </div>
        </div>
    </div>
    {% if goods.goods_discount %}
      <div class="Card-sale">
        {{ goods.goods_discount }}
      </div>
    {% endif %}
</div>

templates/goods/historyview.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
    {% include 'elements/header.html' %}
{% endblock %}
{% load i18n %}
{% block content %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">
            {% translate 'Viewing history' %}
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item">
              <a href="index.html">{% translate 'home' %}</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current">
              <span>{% translate 'Viewing history' %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% translate 'Navigation' %}</strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'account' %}">{% translate 'Personal account' %}</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'profile' %}">{% translate 'Profile' %}</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'history_orders' %}">{% translate 'Order history' %}</a>
                  </li>
                  <li class="menu-item_ACTIVE menu-item">
                    <a class="menu-link" href="{% url 'historyview' %}">{% translate 'Viewing history' %}</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="Section-content">
        <div class="Cards">
          {% if goods_list %}
            {% for goods in goods_list %}
              {% include 'goods/card.html' %}
            {% endfor %}
            {% endif %}
          </div>
          <div class="Pagination">
            <div class="Pagination-ins">
                <a class="Pagination-element Pagination-element_prev" href="#"><img src="{% static 'assets/img/icons/prevPagination.svg' %}" alt="prevPagination.svg"/></a>

                {% for page in paginator.page_range %}
                    {% if page_obj.number == page %}
                        <a class="Pagination-element Pagination-element_current" href="#"><span class="Pagination-text">{{ page }}</span></a>
                    {% else %}
                        <a class="Pagination-element " href="{% url 'historyview' %}?page={{ page }}"><span class="Pagination-text">{{ page }}</span></a>
                    {% endif %}
                    {% endfor %}
                <a class="Pagination-element Pagination-element_prev" href="{% url 'historyview' %}?page={{ page }}"><img src="{% static 'assets/img/icons/nextPagination.svg' %}" alt="nextPagination.svg"/></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block footer %}
     {% include 'elements/footer.html' %}
{% endblock %}

templates/goods/product.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block header %}
    {% include 'elements/header.html' %}
{% endblock %}
{% block content %}
    <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% translate 'Megano Product' %}
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">{% translate 'Home' %}</a></li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% translate 'Product' %}</span></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <div class="Product">
          <div class="ProductCard">
            <div class="ProductCard-look">
              <div class="ProductCard-photo">
                <div class="ProductCard-sale">-15%</div>
                <img src="{{ image_pict_right.image.url }}" alt="card.jpg"/>
              </div>
              <div class="ProductCard-picts">
                {%  for image in images %}
                  <a class="ProductCard-pict ProductCard-pict_ACTIVE" href="{{ image.image.url }}"><img src="{{ image.image.url }}" alt="{{image.name}}png"/></a>
                {%  endfor  %}
              </div>
            </div>
            <div class="ProductCard-desc">
              <div class="ProductCard-header">
                <h2 class="ProductCard-title"> {{goods.name}}
                </h2>
                <div class="ProductCard-info">
                  <div class="ProductCard-cost">
                    <div class="ProductCard-price">{{goods.price}} {% translate "руб." %}
                    </div>
                  </div>
                  <div class="ProductCard-compare">
                      <a class="Card-btn" href="{% url 'compare_add' goods.id %}" ><img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg"/></a>

                  </div>
                </div>
              </div>
              <div class="ProductCard-text">
                <ul>
                      <li>{% translate "Brand" %}: {{goods.brand}}</li>
                </ul>
              </div>
              <div class="ProductCard-cart">
                <div class="ProductCard-cartElement ProductCard-cartElement_amount">
                  <div class="Amount Amount_product">
                    <button class="Amount-remove" type="button">
                    </button>
                    <input class="Amount-input form-input" name="amount" type="text" value="1"/>
                    <button class="Amount-add" type="button">
                    </button>
                  </div>
                </div>
                <div class="ProductCard-cartElement">
                    {% if in_cart_or_not %}
                        <a class="btn btn_primary" href="{% url 'cart' %}"><button class="btn btn_primary">{% translate 'Product in the cart' %}</button></a>
                    {% else %}
                        <a class="btn btn_primary" id="redirect" ><button class="btn btn_primary" id="add_cart" value="{{ goods.id }}">{% translate 'Add To Cart' %}</button></a>
                        <input type="hidden" id="url_from" name="url_from" value="{{request.path}}">
                    {% endif %}
                </div>
              </div>
              <div class="ProductCard-footer">
                <div class="ProductCard-tags">
                  <strong class="ProductCard-tagsTitle">{% translate 'Tags' %}:
                  </strong>
                  <a href="#">{% translate 'Accesories' %}</a>,
                  <a href="#">{% translate 'Creative' %}</a>,
                  <a href="#">{% translate 'Design' %}</a>,
                  <a href="#">{% translate 'Gaming' %}</a>
                </div>
              </div>
            </div>
          </div>
          <div class="Tabs Tabs_default">
            <div class="Tabs-links"><a class="Tabs-link_ACTIVE Tabs-link" href="#description">
              <span>{% translate 'Description' %}</span></a><a class="Tabs-link" href="#sellers">
              <span>{% translate 'Sellers' %}</span></a><a class="Tabs-link" href="#addit">
              <span>{% translate 'AdditionaL Info' %}</span></a><a class="Tabs-link" href="#reviews">
              <span>{% translate 'Reviews' %}({{len_review}})</span></a>
            </div>
            <div class="Tabs-wrap">
              <div class="Tabs-block" id="description">
                <h2>{% translate 'Description' %}
                </h2>
                <p>
                  <strong>{{ goods.describe }}
                  </strong>
                </p><img class="pict pict_right" src="{{ image_pict_right.image.url }}" alt="{{image.name}}.png"/>
                <div class="clearfix">
                </div>
                <div class="table">
                  <table>
                    <tr>
                      <th>{% translate 'Characteristic' %}
                      </th>
                      <th>{% trans 'value' %}
                      </th>
                    </tr>
                    {%  for characteristic in feature  %}
                      <tr>
                        <td>{{characteristic.name.name}}
                        </td>
                        <td> {{characteristic}}
                        </td>
                      </tr>
                    {%  endfor  %}
                  </table>
                </div>
              </div>
              <div class="Tabs-block" id="sellers">
                <div class="Categories Categories_product">
                  {%  for shop in seller %}
                    <div class="Categories-row">
                      <div class="Categories-block Categories-block_info">
                        <div class="Categories-info">
                          <strong>{{shop.seller}}</strong>
                        </div>
                      </div>
                      <div class="Categories-block Categories-price">
                        <strong>€&#32;{{shop.price}}
                        </strong>
                      </div>
                      <div class="Categories-block Categories-button"><a class="btn btn_primary" href="{% url 'cart:addbysellerid' goods.id shop.seller.id %}"><img class="btn-icon" src="{% static 'assets/img/icons/card/cart_white.svg' %}" alt="cart_white.svg"/><span class="btn-content">{% translate 'Buy' %}</span></a></div>
                    </div>
                  {%  endfor  %}
                </div>
              </div>
              <div class="Tabs-block" id="addit">
                <div class="Product-props">
                  <div class="Product-prop">
                    <strong>{% translate 'release date' %}:
                    </strong><span> {{goods.release_date}}</span>
                  </div>
                  <div class="Product-prop">
                    <strong>{% translate 'limit edition' %}:
                    </strong><span> {{goods.limit_edition}}</span>
                  </div>
                  <div class="Product-prop">
                    <strong>{% translate 'category' %}:
                    </strong><span> {{goods.category.title}}</span>
                  </div>
                  <div class="Product-prop">
                    <strong>{% translate 'rating' %}:
                    </strong><span> {{goods.rating}}</span>
                  </div>
                </div>
              </div>
              <div class="Tabs-block" id="reviews">
                <header class="Section-header">
                  <h3 class="Section-title"> {% translate 'Reviews' %}:{{len_review}}</h3>
                </header>
                <div class="Comments">
                  <div class="Comment">
                    {%  for comment in review %}
                        <div class="Comment-column Comment-column_pict">
                          <div class="Comment-avatar"></div>
                        </div>
                        <div class="Comment-column">
                          <header class="Comment-header">
                            <div>
                              <strong class="Comment-title">{{comment.author_name}}
                              </strong><span class="Comment-date">{{comment.date}}</span>
                            </div>
                          </header>
                          <div class="Comment-content">{{comment.text}}</div>
                        </div>
                    {%  endfor  %}
                  </div>
                </div>
                <header class="Section-header Section-header_product">
                  <h3 class="Section-title">{% translate 'Add Review' %}
                  </h3>
                </header>
                <div class="Tabs-addComment">
                    <form class="form" action="../{{goods.id}}/" method="post">
                      {% csrf_token %}
                      <div class="form-group">
                        <textarea class="form-textarea" name="text" id="text" placeholder="Review"></textarea>
                      </div>
                      {% if request.user.is_authenticated %}
                        <div class="form-group">
                          <div class="row">
                            <div class="row-block">
                              <input class="form-input" id="author_name" name="author_name" type="text" value="{{request.user.full_name}}"/>
                            </div>
                            <div class="row-block">
                              <input class="form-input" id="email" name="email" type="email" value={{request.user.email}}>
                            </div>
                          </div>
                        </div>
                      {% else %}
                        <div class="form-group">
                          <div class="row">
                            <div class="row-block">
                              <input class="form-input" id="author_name" name="author_name" type="text"/>
                            </div>
                            <div class="row-block">
                              <input class="form-input" id="email" name="email" type="email"/>
                            </div>
                          </div>
                        </div>
                      {% endif %}
                      <div class="form-group">
                        <button class="btn btn_muted" type="submit">{% translate 'Send feedback' %}</button>
                      </div>
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <script>
    $(document).ready(function (){
        var csrf = $("input[name=csrfmiddlewaretoken]").val();
        $("#add_cart").click(function(){
            $.ajax({
                url: '{% url "cart:add" goods.id%}',
                method: 'post',
                dataType: 'json',
                data: {
                    product_id: {{ goods.id }},
                    count: $(".Amount-input").val(),
                    csrfmiddlewaretoken: csrf
                },
                success: function (response) {
                    document.getElementById('add_cart').textContent = 'В корзинe'
                    document.getElementById('redirect').setAttribute('href', '{% url 'cart:mycart' %}')
                    document.getElementById('CartBlock-price').textContent = response.total_price_disc
                    document.getElementById('CartBlock-price').textContent += 'руб'
                }
            })
        });
    })
    </script>
{% endblock %}

templates/goods/top_product_catalog.html
{% extends "base.htm" %}
{% load i18n %}

{% block top_product_catalog %}
  <div class="Section-content">
    <header class="Section-header">
      <h2 class="Section-title">{% translate 'Popular products' %}
      </h2>
    </header>
    <div class="Cards">
      {% for top_goods in goods %}
         <div class="Card"><a class="Card-picture" href="#"><img src="{% static 'assets/img/content/home/card.jpg' %}" alt="card.jpg"/></a>
            <div class="Card-content">
              <strong class="Card-title"><a href="#">{% translate {{ top_goods.name }} %}</a></strong>
              <div class="Card-description">
                <div class="Card-cost"><span class="Card-priceOld">${% translate {{ top_goods.price }} %}</span><span class="Card-price">$85.00</span>
                </div>
                <div class="Card-category">{% translate {{ top_goods.category }} %}
                </div>
                <div class="Card-hover"><a class="Card-btn" href="#"><img src="{% static 'assets/img/icons/card/bookmark.svg' %}" alt="bookmark.svg"/></a><a class="Card-btn" href="#"><img src="../django-frontend/assets/img/icons/card/cart.svg" alt="cart.svg"/></a><a class="Card-btn" href="../django-frontend/compare.html"><img src="../django-frontend/assets/img/icons/card/change.svg" alt="change.svg"/></a>
                </div>
              </div>
            </div>
            <div class="Card-sale">-60%</div>
          </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}