cart/urls.py
from django.urls import path

from cart.views import CartView, AddProductToCartByProductIdView, AddProductToCartBySellerIdView,\
    DeleteProductFromCartView, ChangePriceAjax, ChangeCountAjax

zapp_name = "cart"

urlpatterns = [
    path("", CartView.as_view(), name="mycart"),
    path(
        "add/<int:id>",
        AddProductToCartByProductIdView.as_view(),
        name="add",
    ),
    path(
        "remove/<int:id>",
        DeleteProductFromCartView.as_view(),
        name="remove",
    ),
    path(
        'change_price',
        ChangePriceAjax.as_view(),
        name='change_price'
    ),
    path(
        'change_count',
        ChangeCountAjax.as_view(),
        name='change_count'
    ),
    path(
        "add/<int:pid>/<int:id>",
        AddProductToCartBySellerIdView.as_view(),
        name="addbysellerid",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/clearcache/', include('banners.urls')),
    path('admin/', admin.site.urls),
    path('', include('customers.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('goods/', include('goods.urls')),
    path('banners/', include('banners.urls')),
    path('customers/', include('customers.urls')),
    path('', include('app_shop.urls')),
    path('orders/', include('orders.urls')),
    path('sale/', include('discounts.urls')),
    path('import/', include('data_import.urls')),
    path('i18n', include('django.conf.urls.i18n')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import UserHistoryOrder, CreateOrder, AddCard, AddSomeoneCard, add_order_for_payment, OrderDetail


urlpatterns = [
    path('history_orders', UserHistoryOrder.as_view(), name='history_orders'),
    path('add_order', CreateOrder.as_view(), name='add_order'),
    path('add_card/<int:pk>/', AddCard.as_view(), name='add_card'),
    path('add_someone_card/<int:pk>/', AddSomeoneCard.as_view(), name='add_someone_card'),
    path('add_card/<int:order_id>/pay/', add_order_for_payment, name='payment'),
    path('add_someone_card/<int:order_id>/pay/', add_order_for_payment, name='payment'),
    path('order_detail/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
]

orders/models.py
from django.core.exceptions import ValidationError
from django.db import models
from goods.models import GoodsInMarket
from customers.models import CustomerUser
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator


def card_validator(message: str):
    def _card_validator(model, field):
        if len(str(field.data)) != 8 and field.data % 2 != 0:
            raise ValidationError(message=message)

    return _card_validator


class Order(models.Model):
    STATUS_VALUE = (
        (0, _('not_pay')),
        (1, _('payed')),
        (2, _('goods_shipped')),
        (3, _('delivered'))
    )
    DELIVERY_METHOD = (
        (0, _('delivery')),
        (1, _('express_delivery'))
    )
    PAYMENT_METHOD = (
        (0, _('online_card')),
        (1, _('online_card_from_someone_else_account'))
    )
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'), null=True)
    status = models.PositiveIntegerField(verbose_name=_('status'), choices=STATUS_VALUE, default=0)
    delivery_method = models.PositiveIntegerField(verbose_name=_('delivery_type'), choices=DELIVERY_METHOD, default=0)
    delivery_city = models.CharField(verbose_name='city', max_length=100, null=True, blank=True)
    delivery_address = models.CharField(verbose_name='address', max_length=200, null=True, blank=True)
    payment_method = models.PositiveIntegerField(verbose_name=_('payment_method'), choices=PAYMENT_METHOD, default=0)
    payment_card = models.PositiveIntegerField(verbose_name=_('payment_card'),
                                               blank=True,
                                               null=True,
                                               )
    total_cost = models.DecimalField(verbose_name='total_cost',
                                     max_digits=10,
                                     null=True,
                                     decimal_places=2,
                                     validators=[MinValueValidator(0.0, message=_("Price can't be less than 0.0"))])
    goods_in_market = models.ManyToManyField(GoodsInMarket,
                                             verbose_name=_('goods_in_market'),
                                             # on_delete=models.DO_NOTHING,
                                             related_name='order')
    customer = models.ManyToManyField(CustomerUser,
                                      verbose_name=_('customer'),
                                      # on_delete=models.DO_NOTHING,
                                      related_name='order')
    order_date = models.DateField(blank=True, null=True, auto_now_add=True)


#class OrderHistory(models.Model):
#    customer = models.ForeignKey(CustomerUser,
#                                 verbose_name=_('order_history'),
#                                 null=True,
#                                 on_delete=models.DO_NOTHING,
#                                 related_name='order_history')
#    order = models.ForeignKey(Order,
    #                          verbose_name=)

orders/forms.py
from django import forms
from orders.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['delivery_method', 'delivery_city', 'delivery_address', 'payment_method',
                  'payment_card', 'goods_in_market', 'customer', ]


class CardNum(forms.Form):
    payment_card = forms.IntegerField()

orders/views.py
import time

from celery.result import AsyncResult
from django.db import transaction
from django.db.transaction import atomic
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView
from config.settings import CACHES_TIME
from orders.services import PaymentGoods
from django.views.decorators.cache import cache_page
from orders.models import Order
from orders.forms import OrderForm, CardNum
from orders.tasks import add_for_payment
from customers.models import CustomerUser
from customers.views import UserAccount
from cart.services import get_cost
from cart.models import CartItems
from cart.services import cart_price


class PaymentGoodsView(View):
    """
    Представление для оплаты товаров.
    """
    payment = PaymentGoods()

    def get(self, request):
        cache_this = cache_page(3600 * CACHES_TIME)
        """
        Реализация метода GET для оплаты товара.
        payment = PaymentGoods()
        payment.payment_for_goods(user_cart, profile) - метод служащий для оплаты товара.
        """

        return render(request, '../..', context={})


class ProductStatusView(View):
    """
    Представление для отслеживания информации о статусе оплаченного товара.
    """
    payment = PaymentGoods()

    def get(self, request):
        cache_this = cache_page(3600 * CACHES_TIME)
        """
        Реализация метода GET для оплаты товара.
        payment = PaymentGoods()
        payment.product_status(profile) - метод служащий для отслеживания статуса заказа.
        """

        return render(request, '../..', context={})


class UserHistoryOrder(ListView):
    template_name = 'orders/history_order.html'
    model = Order
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.filter(customer=self.request.user)


class CreateOrder(CreateView):
    """
    Оформление заказа из позиций корзины.
    В форме пользователь указывает контактные данные, способ оплаты, доставки, адрес. Из позиций корзины формируется
    состав заказа. В зависимости от метода оплаты, по разному определяется счет для оплаты и проверяется условие оплаты.
    После заказ помещается в очередь, где определяется, прошла оплата или нет.
    В случае успешной оплаты заказ передается в доставку.
    """
    model = Order
    form = OrderForm
    template_name = 'orders/order.html'
    context_object_name = 'order'
    success_url = '..'

    def get_context_data(self, **kwargs):
        context = {}
        total_price_disc, total_price, shops, cart = cart_price(self.request)
        context['cart'] = cart
        context['total_price'] = total_price
        context['total_price_disc'] = total_price_disc
        return context

    def post(self, request, *args, **kwargs):
        order_form = OrderForm(request.POST)
        with transaction.atomic():
            order = Order()

            order.quantity = 1
            order.status = 0
            order.delivery_method = order_form.data.get('delivery_method')
            order.delivery_city = order_form.data.get('delivery_city')
            order.delivery_address = order_form.data.get('delivery_address')
            order.payment_method = order_form.data.get('payment_method')
            order.payment_card = order_form.data.get('payment_card')
            order.total_cost = get_cost(request)[1]
            order.save()
            order.customer.add(request.user.id)
            cart = CartItems.objects.filter(user=request.user).values('product_in_shop__id')
            for i in cart:
                order.goods_in_market.add(i['product_in_shop__id'])
            if int(order.payment_method) == 0:
                return redirect(reverse('add_card', kwargs={'pk': order.id}))
                # return redirect(f'./././add_card/{order.id}', order_id=order.id)
            elif int(order.payment_method) == 1:
                return redirect(reverse('add_someone_card', kwargs={'pk': order.id}))
            else:
                return redirect(self.success_url)


class AddCard(UpdateView):
    model = Order
    form_class = OrderForm
    template_name = 'orders/payment.html'


class AddSomeoneCard(UpdateView):
    model = Order
    form_class = OrderForm
    template_name = 'orders/paymentsomeone.html'


class OrderDetail(DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'orders/detail_order.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if not kwargs.get('pay_fail'):
            context['pay_fail'] = False
        else:
            context['pay_fail'] = True
        return context


def add_order_for_payment(request, order_id):
    HttpResponse(request, 'orders/progress_payment.html')
    time.sleep(2)
    card_num = int(request.POST['payment_card'].replace(' ', ''))
    result = add_for_payment(order_id, card_num)
    with transaction.atomic():
        if result:
            order = Order.objects.get(id=order_id)
            if order.status == 0:
                order.status = 1
                order.payment_card = str(card_num)
                order.save()
            CartItems.objects.filter(user=request.user).delete()
            return redirect('catalog')
    order = Order.objects.get(id=order_id)
    if int(order.payment_method) == 0:
        return redirect(reverse('add_card', kwargs={'pk': order.id}))
    elif int(order.payment_method) == 1:
        return redirect(reverse('add_someone_card', kwargs={'pk': order.id}))

templates/orders/detail_order.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% include 'elements/header.html' %}
{% endblock %}

{% block content %}

<div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Заказ {{ order.id }}
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'index' %}">home</a>
            </li>
            <li class="breadcrumbs-item"><a href="{% url 'history_orders' %}">История заказов</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Заказ {{ order.id }}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <div class="Section-content">
          <div class="Orders">
          </div>
          <div class="Order">
            <div class="Order-infoBlock">
              <div class="Order-personal">
                <div class="row">
                  <div class="row-block">
                    <div class="Order-info Order-info_date">
                      <div class="Order-infoType">Дата заказа:
                      </div>
                      <div class="Order-infoContent">{{ order.order_date }}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">ФИО:
                      </div>
                      <div class="Order-infoContent">{{ user.full_name }}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">Телефон:
                      </div>
                      <div class="Order-infoContent">{{ user.phone }}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">E-mail:
                      </div>
                      <div class="Order-infoContent">{{ user.email }}
                      </div>
                    </div>
                  </div>
                  <div class="row-block">
                    <div class="Order-info Order-info_delivery">
                      <div class="Order-infoType">Тип доставки:
                      </div>
                      <div class="Order-infoContent">{{ order.get_delivery_method_display }}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">Город:
                      </div>
                      <div class="Order-infoContent">{{ order.delivery_city }}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">Адрес:
                      </div>
                      <div class="Order-infoContent">{{ order.delivery_address }}
                      </div>
                    </div>
                    <div class="Order-info Order-info_pay">
                      <div class="Order-infoType">Оплата:
                      </div>
                      <div class="Order-infoContent">{{ order.get_payment_method_display }}
                      </div>
                    </div>
                    <div class="Order-info Order-info_status">
                      <div class="Order-infoType">Статус:
                      </div>
                      <div class="Order-infoContent">{{ order.get_status_display }}
                      </div>
                    </div>
                    {% if order.status < 1 %}
                    <div class="Order-info Order-info_error">
                      <div class="Order-infoType">Оплата не прошла:</div>
                      <div class="Order-infoContent">Оплата не выполнена, т.к. вы подозреваетесь в нетолерантности</div>
                    </div>
                    {% endif%}
                  </div>
                </div>
              </div>
              {% for item in order.goods_in_market.all %}
              <div class="Cart Cart_order">
                <div class="Cart-product">
                  <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_pict"><a class="Cart-pict" href="{{ item.goods.get_absolute_url }}">
                      <img class="Cart-img" src="{{ item.goods.goods_image.first.image.url }}" alt="card.jpg"></a>
                    </div>
                    <div class="Cart-block Cart-block_info">
                      <a class="Cart-title" href="{% url 'detail' item.goods.id %}">{{ item.goods.name }}</a>
                      <div class="Cart-desc">{{ item.goods.describe }}
                      </div>
                    </div>
                  </div>
                  <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_seller">
                      <div>Продавец:
                      </div>
                      <div>{{ item.seller }}
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
                <div class="Cart-total">
                  <div class="Cart-block Cart-block_total">
                    <strong class="Cart-title">Итого:<span class="Cart-price">{{ order.total_cost }}</span>
                    </strong>
                  </div>
                  {% if order.status < 1 %}
                  {% if order.payment_method == 0 %}
                  <div class="Cart-block"><a class="btn btn_primary btn_lg" href="{% url 'add_card' order.id %}">Оплатить</a></div>
                  {% else %}
                  <div class="Cart-block"><a class="btn btn_primary btn_lg" href="{% url 'add_someone_card' order.id %}">Оплатить</a></div>
                  {% endif %}
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

{% block footer %}
    {% include 'elements/footer.html' %}
{% endblock %}

  <!--+Middle-->
  <!--    +div.-top-->
  <!--        +breadcrumbs('Главная','Портфолио')-->
  <!--    +Article('portfolio')-->
  <!---->
  <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
  <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
  <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
  <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
  <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
  <script src="{% static 'assets/js/scripts.js' %}"></script>

templates/orders/history_order.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% include 'elements/header.html' %}
{% endblock %}

{% block content %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">История заказов
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'index' %}">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>История заказов</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">Навигация
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item"><a class="menu-link" href="{% url 'account' %}">Личный кабинет</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="../profile/">Профиль</a>
                  </li>
                  <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'history_orders' %}">История заказов</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="{% url 'historyview' %}">История просмотра</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Orders">
          {% for order in request.user.order.all %}
            <div class="Order Order_anons">
              <div class="Order-personal">
                <div class="row">
                  <div class="row-block"><a class="Order-title" href="{% url 'order_detail' order.id %}">Заказ <span class="Order-numberOrder">№ {{ order.id }}</span>&#32;от&#32;<span class="Order-dateOrder">{{ order.order_date }}</span></a>
                  </div>
                  <div class="row-block">
                    <div class="Order-info Order-info_delivery">
                      <div class="Order-infoType">Тип доставки:
                      </div>
                      <div class="Order-infoContent">{{ order.get_delivery_method_display }}
                      </div>
                    </div>
                    <div class="Order-info Order-info_pay">
                      <div class="Order-infoType">Оплата:
                      </div>
                      <div class="Order-infoContent">{{ order.get_payment_method_display }}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">Общая стоимость:
                      </div>
                      <div class="Order-infoContent"><span class="Order-price">{{ order.total_cost }}</span>
                      </div>
                    </div>
                    <div class="Order-info Order-info_status">
                      <div class="Order-infoType">Статус:
                      </div>
                      <div class="Order-infoContent">{{ order.get_status_display }}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
           {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block footer %}
    {% include 'elements/footer.html' %}
{% endblock %}

  <!--+Middle-->
  <!--    +div.-top-->
  <!--        +breadcrumbs('Главная','Портфолио')-->
  <!--    +Article('portfolio')-->
  <!---->
  <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
  <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
  <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
  <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
  <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
  <script src="{% static 'assets/js/scripts.js' %}"></script>

templates/orders/payment.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% include 'elements/header.html' %}
{% endblock %}

{% block content %}
<div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Оплата
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Оплата</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <form class="form Payment" action="pay/{{ order_id }}" method="post">
          {% csrf_token %}
          <div class="Payment-card">
            <div class="form-group">
              <label class="form-label">
                Номер карты
              </label>
              <input class="form-input Payment-bill" id="numero1" name="payment_card" type="text" placeholder="9999 9999" data-mask="9999 9999" data-validate="require pay">
            </div>
          </div>
          <div class="Payment-pay">
            <button class="btn btn_primary" type="submit">Оплатить</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

{% block footer %}
{% include 'elements/footer.html' %}
{% endblock footer %}
<!--+Middle-->
<!--    +div.-top-->
<!--        +breadcrumbs('Главная','Портфолио')-->
<!--    +Article('portfolio')-->
<!---->
<script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
<script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
<script src="{% static 'assets/js/scripts.js' %}"></script>

templates/orders/paymentsomeone.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% include 'elements/header.html' %}
{% endblock %}

{% block content %}
<div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Оплата
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Оплата</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <form class="form Payment" action="pay/{{ order_id }}" method="post">
          {% csrf_token %}
          <div class="Payment-card">
            <div class="form-group">
              <label class="form-label">Номер счета
              </label>
              <input class="form-input Payment-bill" id="numero1" name="payment_card" type="text" placeholder="9999 9999" data-mask="9999 9999" data-validate="require pay">
            </div>
            <div class="form-group"><a class="btn btn_success Payment-generate" href="#">Сгенирировать случайный счет</a>
            </div>
          </div>
          <div class="Payment-pay">
            <button class="btn btn_primary" type="submit">Оплатить</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

{% block footer %}
{% include 'elements/footer.html' %}
{% endblock footer %}
<!--+Middle-->
<!--    +div.-top-->
<!--        +breadcrumbs('Главная','Портфолио')-->
<!--    +Article('portfolio')-->
<!---->
<script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
<script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
<script src="{% static 'assets/js/scripts.js' %}"></script>

templates/orders/progress_payment.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
{% include 'elements/header.html' %}
{% endblock %}

{% block content %}

<div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Ожидание оплаты
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Ожидание оплаты</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <div class="ProgressPayment">
          <div class="ProgressPayment-title">Ждем подтверждения оплаты платежной системой
          </div>
          <div class="ProgressPayment-icon">
            <div class="cssload-thecube">
              <div class="cssload-cube cssload-c1"></div>
              <div class="cssload-cube cssload-c2"></div>
              <div class="cssload-cube cssload-c4"></div>
              <div class="cssload-cube cssload-c3"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

{% block footer %}
{% include 'elements/footer.html' %}
{% endblock footer %}
<!--+Middle-->
<!--    +div.-top-->
<!--        +breadcrumbs('Главная','Портфолио')-->
<!--    +Article('portfolio')-->
<!---->
<script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
<script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
<script src="{% static 'assets/js/scripts.js' %}"></script>